"""
Atom feed example
=================

Generate a small Atom feed with domonic's namespaced XML constructors.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import domonic.xml.atom as atom

OUTPUT = Path(__file__).with_suffix(".xml")


def build_feed():
    return atom.feed(
        atom.title("domonic release notes"),
        atom.subtitle("Tiny generated Atom feed"),
        atom.id("tag:example.com,2026:domonic"),
        atom.updated("2026-08-22T12:00:00Z"),
        atom.link(_href="https://example.com/domonic/", _rel="alternate"),
        atom.link(_href="https://example.com/domonic/atom.xml", _rel="self"),
        atom.author(atom.name("byteface"), atom.email("hello@example.com")),
        atom.entry(
            atom.title("XML helpers grew up"),
            atom.id("tag:example.com,2026:domonic/xml-helpers"),
            atom.updated("2026-08-22T12:00:00Z"),
            atom.published("2026-08-22T12:00:00Z"),
            atom.summary("Atom constructors now mirror the XML tag names cleanly."),
            atom.content("Generated by domonic.xml.atom", _type="text"),
            atom.create_element("app:edited", "2026-08-22T12:05:00Z"),
        ),
        xml_lang="en",
        **{"xmlns:app": "http://www.w3.org/2007/app"},
    )


def render_xml(node):
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + str(node)


if __name__ == "__main__":
    OUTPUT.write_text(render_xml(build_feed()), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
