"""
MathML example
==============

Render a small MathML page with the MathJax shim in place.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from domonic.CDN import CDN_JS
from domonic.html import *
from domonic.xml.mathml import *


OUTPUT = Path(__file__).with_suffix(".html")


def quadratic_formula():
    return math_(
        mrow(
            mi("x"),
            mo("="),
            mfrac(
                mrow(
                    mo("-"),
                    mi("b"),
                    mo("+"),
                    msqrt(
                        mrow(
                            msup(mi("b"), mn("2")),
                            mo("-"),
                            mn("4"),
                            mi("a"),
                            mi("c"),
                        )
                    ),
                ),
                mrow(mn("2"), mi("a")),
            ),
        ),
        _display="block",
        _xmlns="http://www.w3.org/1998/Math/MathML",
    )


def pythagoras():
    return math_(
        mrow(
            msup(mi("a"), mn("2")),
            mo("+"),
            msup(mi("b"), mn("2")),
            mo("="),
            msup(mi("c"), mn("2")),
        ),
        _display="block",
        _xmlns="http://www.w3.org/1998/Math/MathML",
    )


def build_page():
    return html(
        head(
            meta(_charset="utf-8"),
            meta(_name="viewport", _content="width=device-width, initial-scale=1"),
            title("domonic MathML"),
            script(_id="MathJax-script", _defer="", _src=CDN_JS.MATHML),
            style(
                """
                body {
                    font-family: system-ui, sans-serif;
                    margin: 2rem;
                    line-height: 1.5;
                    color: #1d2733;
                }
                main {
                    max-width: 42rem;
                }
                section {
                    border-top: 1px solid #d7dde5;
                    padding: 1.25rem 0;
                }
                math {
                    font-size: 1.35rem;
                }
                """
            ),
        ),
        body(
            main(
                h1("MathML generated by domonic"),
                p("The MathJax script in the head acts as the browser shim."),
                section(h2("Quadratic formula"), quadratic_formula()),
                section(h2("Pythagoras"), pythagoras()),
            )
        ),
    )


if __name__ == "__main__":
    render(build_page(), str(OUTPUT))
    print(f"Wrote {OUTPUT}")
