"""
RSS feed example
================

Generate an RSS 2.0 feed with Atom, Dublin Core, content and media extensions.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import domonic.xml.rss as rss


OUTPUT = Path(__file__).with_suffix(".xml")


def build_feed():
    return rss.rss(
        rss.channel(
            rss.title("domonic updates"),
            rss.link("https://example.com/domonic/"),
            rss.description("Small RSS feed generated with domonic.xml.rss"),
            rss.language("en-gb"),
            rss.generator("domonic"),
            rss.atom_link(
                _href="https://example.com/domonic/rss.xml",
                _rel="self",
                _type="application/rss+xml",
            ),
            rss.sy_updatePeriod("daily"),
            rss.sy_updateFrequency("1"),
            rss.item(
                rss.title("RSS helpers now handle namespaces"),
                rss.link("https://example.com/domonic/xml"),
                rss.guid(
                    "https://example.com/domonic/xml",
                    is_perma_link="true",
                ),
                rss.pubDate("Sat, 22 Aug 2026 12:00:00 GMT"),
                rss.dc_creator("byteface"),
                rss.content_encoded("<p>Generated by domonic.xml.rss</p>"),
                rss.media_content(
                    _url="https://example.com/domonic.png",
                    _type="image/png",
                    _width="1200",
                    _height="630",
                ),
            ),
        ),
        xmlns_atom=rss.XMLNS_ATOM,
        xmlns_content=rss.XMLNS_CONTENT,
        xmlns_dc=rss.XMLNS_DC,
        xmlns_media=rss.XMLNS_MEDIA,
        xmlns_sy=rss.XMLNS_SY,
    )


def render_xml(node):
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + str(node)


if __name__ == "__main__":
    OUTPUT.write_text(render_xml(build_feed()), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
